version: '3'

services:
  node-app:
    image: my-node-app
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: defaultdb
